# Generated by Django 4.2.4 on 2023-09-04 07:02

from django.db import migrations, models
import module.helpers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_alter_article_options_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=module.helpers.RandomFileName('image'), verbose_name='อัพโหลดรูปภาพ')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
