# Generated by Django 4.2.4 on 2023-09-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
