# Generated by Django 4.2.4 on 2023-09-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_rename_image_photo_alter_photo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
