# Generated by Django 4.2.4 on 2023-09-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_article_end_date_article_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='start_date',
        ),
    ]
